FROM mcr.microsoft.com/dotnet/sdk:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR "/WebServiceM2/Messaging"
COPY ["Messaging.fsproj", "/"]
COPY ["../WebServiceM2Lib/WebServiceM2Lib.fsproj", "WebServiceM2Lib/"]
RUN dotnet restore "Messaging.fsproj"
COPY . .
WORKDIR "/WebServiceM2/Messaging"
RUN dotnet build "Messaging.fsproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "Messaging.fsproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "WebServiceM2.dll"]